### ISSUE TITLE
how to use this tool?

### ISSUE THREAD

**Issue by roger125** [JanAhrens/youtube-comments#1]
Hi Team,
   how to use this tool?
   do you mean put my own API_KEY into the "-d key="${API_KEY}" \" in the named file "download"?
   and then what to do after i input the API_KEY?
   
   not so family about the coding process, so...your help is greatly appreciated.

**Comment by JanAhrens** [comment]
Hi @roger125,

This tool is really just a tiny hack that was useful for me almost two years ago. I haven't validated if it still works. 

You need some experience with the command-line in order to use it. As the README mentions, you need to create a file called `local-settings.sh` in the same directory you downloaded the rest of this repository. In that file you then put the YouTube API key that you created for yourself. 

As I already wrote: I can't guarantee that I'll still work for you. I hope that this is helpful for you.
